BlackSmith:
    prices:
        woodbase: 10
        stonebase: 20
        ironbase: 60
        goldbase: 50
        diamondbase: 200
        chainbase: 600
    global:
        ecoEngine: BOSECONOMY