name: Blacksmith
main: com.github.Holyvirus.Blacksmith.BlackSmith
version: 2.1
commands:
   blacksmith:
      description: View possible enchant formats!
      usage: /<command> enchants
   bs:
      description: View possible enchant formats!
      usage: /<command> enchants
permissions:
    blacksmith.*:
        description: Grants access to all BlackSmith interactions
        childs:
            blacksmith.place.value: true
            blacksmith.place.repair: true
            blacksmith.place.free: true
            blacksmith.place.dismantle: true
            blacksmith.place.enchant: true
            blacksmith.remove.value: true
            blacksmith.remove.repair: true
            blacksmith.remove.free: true
            blacksmith.remove.dismantle: true
            blacksmith.remove.enchant: true
            blacksmith.use.value: true
            blacksmith.use.repair: true
            blacksmith.use.free: true
            blacksmith.use.kill: true
            blacksmith.use.dismantle: true
            blacksmith.use.enchant: true
    blacksmith.use.*:
        description: Grants access to all BlackSmith use interactions
        childs:
            blacksmith.use.value: true
            blacksmith.use.repair: true
            blacksmith.use.free: true
            blacksmith.use.kill: true
            blacksmith.use.dismantle: true
            blacksmith.use.enchant: true
    blacksmith.place.*:
        description: Grants access to all BlackSmith placement interactions
        childs:
            blacksmith.place.value: true
            blacksmith.place.repair: true
            blacksmith.place.free: true
            blacksmith.place.kill: true
            blacksmith.place.dismantle: true
            blacksmith.place.enchant: true
    blacksmith.remove.*:
        description: Grants access to all BlackSmith remove interactions
        childs:
            blacksmith.remove.value: true
            blacksmith.remove.repair: true
            blacksmith.remove.free: true
            blacksmith.remove.kill: true
            blacksmith.remove.dismantle: true
            blacksmith.remove.enchant: true
    blacksmith.use.value:
        description: Grants ability to use Value signs
        default: true
    blacksmith.use.repair:
        description: Grants ability to use Repair signs
        default: true
    blacksmith.use.free:
        description: Grants ability to use Free signs
        default: true
    blacksmith.use.kill:
        description: Grants ability to use Kill signs
        default: true
    blacksmith.use.dismantle:
        description: Grants ability to use Dismantle signs
        default: true
    blacksmith.use.enchant:
        description: Grants ability to use Enchant signs
        default: true
    blacksmith.place.value:
        description: Grants ability to place Value signs
        default: op
    blacksmith.place.repair:
        description: Grants ability to place Repair signs
        default: op
    blacksmith.place.free:
        description: Grants ability to place Free signs
        default: op
    blacksmith.place.kill:
        description: Grants ability to place Kill signs
        default: op
    blacksmith.place.dismantle:
        description: Grants ability to place Dismantle signs
        default: op
    blacksmith.place.enchant:
        description: Grants ability to place Enchant signs
        default: op
    blacksmith.remove.value:
        description: Grants ability to remove Value signs
        default: op
    blacksmith.remove.repair:
        description: Grants ability to remove Repair signs
        default: op
    blacksmith.remove.free:
        description: Grants ability to remove Free signs
        default: op
    blacksmith.remove.kill:
        description: Grants ability to remove Kill signs
        default: op
    blacksmith.remove.dismantle:
        description: Grants ability to remove Dismantle signs
        default: op
    blacksmith.remove.enchant:
        description: Grants ability to remove Enchant signs
        default: op
    blacksmith.enchant.unsafe:
        description: Grants ability to enchant unsafely!
        default: op
    blacksmith.enchant.free:
        description: Grants ability to enchant for free!
        default: op